### ISSUE TITLE
Modalizing

### ISSUE THREAD

**Issue by rickydazla** [Tricky3/mailchimpPopUp#2]
Hey @jayvin I am running into some inconsistent issues, I think caused by some confusion between me / you / @trajceoh as to how these popups (should) work...

My initial vision was for the CSS modalHolder to have display:none and the script would then add the "modalize" class. The modalize class has display block so that would show the modal and then a bunch of other associated attributes would then apply to child elements. 

However, I think the script is now using show() and hide() as I see that in various implementations there is an inline display:none and / or the modalize class is already applied. I still see refs to "modalize" in the popup script. 

Can you clarify what is happening and/or fix it up? I would like the script to add/remove the modalize class. However, I see the benefit of show/hide as it can be used to fade the modal instead of just boshing it in. Can we do a combo of both? i.e. script adds "modalize" and then fades it in? Maybe we can add options for fade true/false and if true a setting for speed of fade...

**Comment by rickydazla** [comment]
@jayvin I know this is old, but just to respond anyway in case I haven't on Asana... why not?

**Comment by rickydazla** [comment]
I think previously we were doing some config in the `snippets/mailchimp-signup-script.liquid` file but now it is all abstracted to `config/settings.html`... As I recall, we had originally copied the `mailchimp.popup.js.liquid` file directly from MailChimp just to have in on the same server but now you have hacked it some so it all belongs to us!

**Comment by jayvin** [comment]
@rickydazla, coming to this one, from your first comment.
Currently, the form becomes visible like this
setTimeout(function () {
            T3MCP.Popup.fadeIn().addClass('modalize');
            _MCPopupCustomCallBack.OnShow();
        }, delay);

The add class 'modalize' was not there, I have just added it.
For hiding, default jquery hide is called. 

Is that the behavior that you wanted, if not let me know, I will do the changes.

**Comment by rickydazla** [comment]
Seems like `.attr('hidden',true)` would be better, [see Paul Irish's discussion here](https://twitter.com/paul_irish/status/564578414305509376) re: [performance of hide()](https://github.com/jquery/jquery.com/issues/88#issuecomment-72400007)

**Comment by jayvin** [comment]
For the hide, I will just remove the modalize class. 
What about show? Should we fadeIn the popup as well or just modalize it?

**Comment by rickydazla** [comment]
Just add `modalize` and `attr('hidden',false)`. No effects just :bomb:

**Comment by rickydazla** [comment]
* I have noticed that on some of our sites the modal fades in before the background images has loaded...

**Comment by jayvin** [comment]
Yes, actually I know why this fading thing is there, I remember some client wanted to have a fading effect and since then, this piece of code has remained into the plugin. :)

**Comment by jayvin** [comment]
Done, removed fadeIn effect and popup will hide by removeClass 'modalize' instead of .hide() function..
