### ISSUE TITLE
Custom Responses (esp. for Coupon Code Delivery)

### ISSUE THREAD

**Issue by rickydazla** [Tricky3/mailchimpPopUp#3]
@jayvin I know we have done some custom work to make this possible, wondering if we can make it standard option in the plugin(s) now? i.e. have a success callback with text that can be populated via `config/settings.html`.

**Comment by jayvin** [comment]
@rickydazla : So after successfull registration, default things that are done are as such:
1. Save cookie,
2. Default callback that tracks this as a GA event
3. Popup is hidden
=> So lets have this option named like, _MCAllowDefaultSuccessCallback, it will be true by default.
and when this variable is set to false, only first and second steps above will be executed. We will manually call the function to hide the popup after we have displayed the text from the config/settings.html. Question about, the text will be displayed in the popup itself, right? Is it already active on bluekicks?

**Comment by jayvin** [comment]
@rickydazla : Instead of adding _MCAllowDefaultSuccessCallback variable, what if we add something like below : 
_MCPreconfiguredSuccessMessage = {{ settings.mailchimp_success_message }};

If the above varible is null or empty, default mailchimp success message will be displayed else this text will be displayed.

**Comment by rickydazla** [comment]
I think I would like three scenarios
* standard server response(s) from the chump
* modified response(s) text
* entirely modified callback

Blu Kicks currently does the last I think, so let's test it there. I will update their dev store for you to work there.

**Comment by jayvin** [comment]
Cool, all scenarios will fit in. 
So we will have two variables,
_AllowDefaultCallBack => true or false
_CustomSuccessMessage => any text you want..

**Comment by jayvin** [comment]
OK so only 1 variable is needed, 
https://github.com/Tricky3/mailchimpPopUp/blob/master/snippets/mailchimp-signup-script.liquid, line 2.
I have added it to bluekicks also, have a look and let me know.

**Comment by jayvin** [comment]
Also GA trackers have also been activated for bluekicks.
